### ISSUE TITLE
Invert Y axis

### ISSUE THREAD

**Issue by trinity5150** [undefinedthegamebugs/undefinedthegamebugs#10]
There is no selection to invert the Y axis. Really?

**Comment by undefinedthegame** [comment]
@trinity5150 Thanks for the report!

Do you mean for the player control (looking up and down), or for something building system related?

**Comment by trinity5150** [comment]
For the player controls when looking up or down just like if you were playing Portal 2 or Far Cry 5 for example.

**Comment by undefinedthegame** [comment]
Will add that!
Thanks!

**Comment by trinity5150** [comment]
Thank you for that.

**Comment by undefinedthegame** [comment]
We just added this on the hotfix which just came out :)
We hope you think about adapting the review on steam :) @trinity5150
