### ISSUE TITLE
Unreal engine keeps crashing.

### ISSUE THREAD

**Issue by Olympus149** [undefinedthegamebugs/undefinedthegamebugs#11]
![image](https://user-images.githubusercontent.com/89293181/130723740-f16ae2b2-e75d-4c5d-8e0d-c078768b55a1.jpeg)

Open game 
load a saved game. New games don't crash only older
Walk in any direction for like 20 secs then game crashes.

**Comment by undefinedthegame** [comment]
Hi! Thanks for the bug report!
Unfortunately we can not recreate the bug! Could you please zip your whole SaveGames Folder (C:\Users\USERNAME\AppData\Local\SandboxGame\Saved\SaveGames) and post in in here so we can try out your save game!

Thank you!

**Comment by undefinedthegame** [comment]
fix will come in next update
