### ISSUE TITLE
Some trees don't have a hitbox

### ISSUE THREAD

**Issue by streams-in-silence** [undefinedthegamebugs/undefinedthegamebugs#7]
Description of the bug:
In the jungle spawn area, there are some trees that don't have a hitbox and you can just run through them.
![20210820230516_1](https://user-images.githubusercontent.com/11992626/130293806-090a4c73-5093-45b3-b7f8-060b7e14a64d.jpg)

Steps to reproduce:
1. Start a new game
2. Select the spawn area: Jungle
3. Leave the rest of the settings untouched
4. Run around and find some trees without hitbox (see attached image).

**Comment by undefinedthegame** [comment]
Thank you for the bug report!

**Comment by undefinedthegame** [comment]
This will be fixed with the next patch.
