### ISSUE TITLE
Trees respawning 

### ISSUE THREAD

**Issue by Olympus149** [undefinedthegamebugs/undefinedthegamebugs#8]
This might not be a bug but the trees respawn so they will respawn inside building unless they don't when actual blocks are placed.(not had time to test yet)
![IMG_5825](https://user-images.githubusercontent.com/89293181/130313963-e1a137b0-d941-443d-9dd8-6f2315615320.jpg)
![IMG_5824](https://user-images.githubusercontent.com/89293181/130313964-936a9cb1-0791-4749-a8df-c7a8feb9286b.jpg)

Steps to reproduce:
1-Close game to main menu or just exit game  
2- Reopen saved game and they have respawned 

(sry about quality took on phone camera haha)

**Comment by undefinedthegame** [comment]
Thanks for the bug report! We added it to our internal backlog!

**Comment by undefinedthegame** [comment]
fixed internally. will come out with the next patch :)
