### ISSUE TITLE
Spawned below ground and fell further

### ISSUE THREAD

**Issue by 7imC** [undefinedthegamebugs/undefinedthegamebugs#9]
The first time that I started a game I spawned below ground and fell further down and away from the worlds surface.
The game I created had all the graphics set to the highest level of detail, was set to start in the forest and was set to creative.
I resolved the situation by selecting 'Suicide' and therefore respawning.

**Comment by undefinedthegame** [comment]
Thanks for the bug report! We will take a look at this and added it to our internal issue system!

**Comment by undefinedthegame** [comment]
We couldn't recreate the bug but we changed some code which should fix it. if this happens again, just let us know. the fix will come in the next patch (version 1.4.0)
